name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy: 
      matrix:
        features: ["", "hash-sha1,hash-sha2,hash-xxh"]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          toolchain: "stable"

      - name: Build feature set ${{ matrix.features }}
        run: cargo build --no-default-features --features "${{ matrix.features }}"

      - name: Test feature set ${{ matrix.features }}
        run: cargo test --no-default-features --features "${{ matrix.features }}"

